# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/hello.sh'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      docker run --rm -i -v $(System.DefaultWorkingDirectory)/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < Dockerfile.Alpha || true
      docker run --rm -i -v $(System.DefaultWorkingDirectory)/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < Dockerfile.Beta || true
      docker run --rm -i -v $(System.DefaultWorkingDirectory)/.hadolint.yaml:/.config/hadolint.yaml hadolint/hadolint < Dockerfile.Gama || true
  displayName: 'Run a hadolint multi-line script'

- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/hadolint2.sh'