# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Bash@3
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/hello.sh'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
      chmod +x /bin/hadolint
      hadolint --config '$(System.DefaultWorkingDirectory)/.hadolint.yaml' Dockerfile
  displayName: 'Run a hadolint multi-line script'